---
abstract: 'Class for creating routing for web interface'
author:
  - 'Igor Sverdlov <igor-sverdlov@mail.ru>'
build_requires:
  Digest::MD5: 0
  QBit::TWebInterface::Request: 0
  TWebInterface: 0
  Test::Deep: 0
  Test::More: 0
  lib::abs: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: QBit-WebInterface-Routing
requires:
  Exception: 0
  Exception::Request::UnknownMethod: 0
  Exception::WebInterface::Controller::CSRF: 0
  File::Path: 0
  POSIX: 0
  QBit::Application: 0
  QBit::Class: 0
  QBit::WebInterface: 0
  QBit::WebInterface::Response: 0
  URI::Escape: 0
  base: 0
  qbit: 0
  strict: 0
version: 0.002
